### ISSUE TITLE
inputs <file> is not working

### ISSUE THREAD

**Issue by cryptocake** [shesek/bcash-instadump#1]
I'm not getting any response from the bcash-tx and bcash-instadump scripts when using an inputs file.
It's only returning the script's "help" page for me.

The file's format is:
txid,vout,amount,key
txid,vout,amount,key

When inputting one of those lines individually, it works (not in the file).

**Comment by shesek** [comment]
Fixed in efbf30d, released in v0.2.7. Run `npm install bcash-instadump@0.2.7` and try again.

Thanks for the report!

**Comment by cryptocake** [comment]
Thanks!
