### ISSUE TITLE
Multiple transaction rejected by network rules

### ISSUE THREAD

**Issue by cryptocake** [shesek/bcash-instadump#2]
After bcash-instadump using an inputs file list (which you fixed, thanks!) I get a network rejection:

"(error) The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation))"

It will show me:
```
(info) electrum command: blockchain.transaction.broadcast [ 
<snipping the HUGE output>
(error) The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation))
<snipping the exact same HUGE output>
```

**Comment by shesek** [comment]
1. It looks like some of the unspent outputs are not controlled by their associated keys. Are you sure the inputs you provided are correct?

2. You can try running `bcash-utxo <address>` to see the current unspent outputs available in `<address>` on the bcash network and verify that it matches your inputs list. (note that `bcash-instadump` expects keys, while `bcash-utxo` works with addresses)

3. Did you export the unspent outputs and keys using the Electrum snippet on the README? If so, this might've extracted some `p2sh` multi-signature addresses, which won't work (the tool currently supports `p2pkh` scripts only).

**Comment by cryptocake** [comment]
Ah.... I was using compressed WIF keys :) uncompressed worked 👍 
Thank you for the help!
