### ISSUE TITLE
Dumping from P2SH inputs bounty

### ISSUE THREAD

**Issue by ghost** [shesek/bcash-instadump#3]
I could pay an equivalent of 0.494159bch **in bitcoins** (approximately 0.031415btc at time of writing) to someone who implements dumping from p2sh inputs.

As my github activity is negligible, I would pay this bounty in advance making @shesek a trusted party (can consider other options as well such as 2-3 bitcoin multisig transaction). The final payout sum will be determined at time of pull request merge (if merge is delayed but code works - at time of pull request).

Thanks in advance.

P.S. I specified bounty in BCH so there is a stimulus to develop this functionality as soon as possible (as in my opinion the price of bcash will further go down). The 0.494159BCH converted to BTC is **guaranteed** payout amount even in a scenario of bch price increase.

**Comment by Crypt-iQ** [comment]
I could do this.  I assume the current code only allows for p2pkh?

**Comment by ghost** [comment]
> I assume the current code only allows for p2pkh?
> 
Yes, as stated in the readme 'contributing' section:
>Multi-signature support (currently only p2pkh scripts are supported)

I am asking for P2SH support.

**Comment by ghost** [comment]
closed as there is no interest from the community and copay will [update](https://github.com/bitpay/bitcore-lib/issues/150#issuecomment-321542970) their utility in a few days
